

                       term  ::=  argument ( <NO_WHITESPACE>      (111)

                                           | ( `( "+" | "-" )` )  (110) ) argument

                               |  "-"` argument (109)


                               ;

